### ISSUE TITLE
JavaScript error with WordPress 4.x due to missing depenency

### ISSUE THREAD

**Issue by teamtacho** [CalderaWP/Caldera-Forms#3089]
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* Yes

## Is This A Feature Request?
* please see the support forum for your plugin at wordpress. There are many issue reported regarding the same problem.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
1.8.2

## What Is The Unexpected Behaviour?
Button changes color but email isn't sent.

## What PHP Errors Have You Logged While Reproducing This Bug?
see other issues the support forum for your plugin at wordpress

## What JavaScript Errors Have You Seen While Reproducing This Bug?
see other issues the support forum for your plugin at wordpress

**Comment by meentix** [comment]
Same problem here...

**Comment by teamtacho** [comment]
Hi
Version 1.8.1 worked for me without any sending problem.

**Comment by meentix** [comment]
Yeah, Ive rolled back to 1.7.6 because of other issues, so maybe "a fix" for you would be to rollback to 1.8.1 until the issue is fixed in a new version.

**Comment by teamtacho** [comment]
If I uncheck ajax submission in the form settings it works!

**Comment by meentix** [comment]
I know, but I need ajax submission.

**Comment by New0** [comment]
Hello @teamtacho , @meentix , could you provide the Debug information and an export of the form this happens please ?
You'll find the Debug information at Caldera Forms -> Support under the Debug information tab

**Comment by teamtacho** [comment]
Here is the info:
Short Debug Information
WordPress Version: 4.9.8PHP Version: 7.2.15MySQL Version: 5.6.42Caldera Forms Version: 1.8.2WP_DEBUG:
Full Debug Information
WordPress Version: 4.9.8

PHP Version: 7.2.15

MySQL Version: 5.6.42

Server Software: Apache/2.4.37 (Unix)

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36


[teamnachrichten-export.zip](https://github.com/CalderaWP/Caldera-Forms/files/2962685/teamnachrichten-export.zip)

**Comment by New0** [comment]
Thank you @teamtacho , this could be a duplicate of #3090 , could you provide the list of plugins from the debug information please ?

**Comment by teamtacho** [comment]
Currently Active Theme: i-max: 1.4.0

Plugins:

Akismet Anti-Spam: 4.1.1 Aktiv
amr shortcode any widget: 3.7 Aktiv
Archives Calendar Widget: 1.0.12 Aktiv
ARCW Popover Addon: 0.1.4 Aktiv
ARI Fancy Lightbox: 1.3.6 Aktiv
Attachment Pages Redirect: 1.1 Aktiv
Author Avatars List: 1.16 Aktiv
Avatar Manager: 1.6.1 Aktiv
Better Font Awesome: 1.7.1 Aktiv
Breadcrumb NavXT: 6.2.1 Aktiv
Caldera Forms: 1.8.2 Aktiv
Change Password Protected Message: 1.2.2 Aktiv
Classic Text Widget: 1.0.1 Aktiv
CMB2: 2.6.0 Aktiv
CMS Tree Page View: 1.6 Aktiv
Code Snippets: 2.13.2 Aktiv
Content timeline: 4.4.5 Aktiv
Custom Scrollbar: 1.3.2 Aktiv
Decent Comments: 1.6.0 Aktiv
Delightful Downloads: 1.6.6 Aktiv
Ditty News Ticker: 2.2.1 Aktiv
Duplicate Post: 3.2.2 Aktiv
Easy Timeout Session: 1.1 Aktiv
Events Made Easy: 2.1.10 Aktiv
Events Made Easy Frontend Submit: 1.0.37 Aktiv
Favicon by RealFaviconGenerator: 1.3.15 Aktiv
Frontend Publishing: 2.5.0 Aktiv
giWeather: 1.5.1 Aktiv
Google Maps Easy: 1.9.15 Aktiv
Google Maps Easy PRO: 1.3.6 Aktiv
Gwolle Guestbook: 3.1.1 Aktiv
Image Widget: 4.4.7 Aktiv
Jeffrey Keijzer WP Login Count: 1.0 Aktiv
Login Logo: 0.9.0 Aktiv
Master Slider: 3.5.3 Aktiv
Nav Menu Roles: 1.9.3 Aktiv
No Right Click Images Plugin: 3.4 Aktiv
Page scroll to id: 1.6.4 Aktiv
Recent Posts Widget With Thumbnails: 6.5.0 Aktiv
Remove Dashboard Access: 1.1.3 Aktiv
ReOrder Post Within Categories: 1.8.1 Aktiv
Responsive Tabs: 4.0.0 Aktiv
Shortcoder: 4.3 Aktiv
Shortcodes Ultimate: 5.3.0 Aktiv
Simple Page Sidebars: 1.2.1 Aktiv
SimpleRestrict: 1.0.2 Aktiv
Subscribe to Comments Reloaded: 190305 Aktiv
teamtacho-extras: 1.1 Not Active
TemplatesNext ToolKit: 3.1.6 Aktiv
Thin Out Revisions: 1.8.3 Aktiv
TinyMCE Advanced: 5.0.1 Aktiv
User Session Control: 0.3.1 Aktiv
User Submitted Posts: 20190220 Aktiv
Widget Logic: 5.9.0 Aktiv
WP-Members: 3.2.5.1 Aktiv
wpDataTables: 2.4 Aktiv
WP Editor Comments Plus: 1.1.4 Aktiv
Yoast SEO: 9.7 Aktiv

**Comment by Tofandel** [comment]
Same here there is a js error on the page
```
Uncaught TypeError: Cannot read property 'SelectControl' of undefined
    at Object.<anonymous> (index.min.js:1)
    at e (index.min.js:1)
    at Object.<anonymous> (index.min.js:1)
    at e (index.min.js:1)
    at index.min.js:1
    at index.min.js:1
index.min.js:30 Uncaught TypeError: Cannot read property 'render' of undefined
    at HTMLDocument.<anonymous> (index.min.js:30)
    at HTMLDocument.dispatch (jquery-3.1.1.min.js:3)
    at HTMLDocument.q.handle (jquery-3.1.1.min.js:3)
    at Object.trigger (jquery-3.1.1.min.js:4)
    at HTMLDocument.<anonymous> (jquery-3.1.1.min.js:4)
    at Function.each (jquery-3.1.1.min.js:2)
    at a.fn.init.each (jquery-3.1.1.min.js:2)
    at a.fn.init.trigger (jquery-3.1.1.min.js:4)
    at HTMLFormElement.<anonymous> (caldera-forms-front.min.js:5)
    at Function.each (jquery-3.1.1.min.js:2)
2index.min.js:30 Uncaught TypeError: h.getAllFieldValues is not a function
    at HTMLDocument.<anonymous> (index.min.js:30)
    at HTMLDocument.dispatch (jquery-3.1.1.min.js:3)
    at HTMLDocument.q.handle (jquery-3.1.1.min.js:3)
    at Object.trigger (jquery-3.1.1.min.js:4)
    at HTMLDocument.<anonymous> (jquery-3.1.1.min.js:4)
    at Function.each (jquery-3.1.1.min.js:2)
    at a.fn.init.each (jquery-3.1.1.min.js:2)
    at a.fn.init.trigger (jquery-3.1.1.min.js:4)
    at Object.init (caldera-forms-front.min.js:1)
    at HTMLFormElement.<anonymous> (jquery-baldrick.min.js:1)
```

This is because there is no localized item 'wp' on the page

Please fix this issue quickly, make the latest version completely useless, thanks

**Comment by Shelob9** [comment]
@New0 Look at the debug info from @teamtacho `WordPress Version: 4.9.8`

`Uncaught TypeError: Cannot read property 'SelectControl' of undefined` is because wp-component isn't a registered script. Same with any gutenberg package.

So @teamtacho your workaround is activate Gutenberg or upgrade to WordPress.org BTW We do not support jQuery 3.0. Its never a great idea to switch from the bundled version in WordPress. I think on our site I load it from a CDN, but using the same version number.

@Shelob9 - how did you not think of this?

@New0 - I guess we need to bundle all of the `wp-*` dependencies in Caldera Forms and enqueue them if not already enqueued. It looks like core loads them on the default priority so we can use the same hooks, with a higher priority -> https://github.com/WordPress/WordPress/blob/master/wp-includes/default-filters.php#L498-L501

**Comment by Shelob9** [comment]
Relevant info: https://github.com/CalderaWP/Caldera-Forms/issues/2860#issuecomment-451554557

**Comment by nathanhere** [comment]
Experiencing same issues here. I'll need to go through all of my forms to disable ajax i guess....

**Comment by teamtacho** [comment]
Hi Guys
I switched back to 1.7.6 and everything works well.

**Comment by meentix** [comment]
> Hi Guys
> I switched back to 1.7.6 and everything works well.

Yeah, unfortunately caldera forms gets more buggy and buggy with every new version :-(

**Comment by New0** [comment]
Hello @teamtacho , did you test updating to 1.8.3 ?

**Comment by teamtacho** [comment]
Hi
Not yet because the issue is allocated to milestone 1.8.4 and I didn't do the update to 1.8.3.

**Comment by Shelob9** [comment]
Close via #3100

@teamtacho is was fixed in 1.8.3

**Comment by teamtacho** [comment]
Hi Shelob 9
Sorry for being late but today I tested the BCC field with CF Version 1.8.11.
I still get the error message "wrong email address" in the BCC field if I put in two email addresses comma separated.

Best Regards Michael

Here are my debug info:
WordPress Version: 5.3.2

PHP Version: 7.3.16

MySQL Version: 5.6.42

Server Software: Apache/2.4.41 (Unix)

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

Session Save Path: 2;/var/tmp

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
Redis: No
Object Cache:

Apc: No
Apcu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Currently Active Theme: i-max: 1.4.2
