### ISSUE TITLE
Upload Field (File) Not Allowing More than 1 File 

### ISSUE THREAD

**Issue by Science4me** [CalderaWP/Caldera-Forms#3385]
## Do You Need Immediate Help?
No

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
    WordPress Version: 5.2.4PHP Version: 7.3.11MySQL Version: 5.7.23Caldera Forms Version: 1.8.7WP_DEBUG: 

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
The File Upload Field does not allow more than 1 file even when Add Multiple is Ticked.

## What PHP Errors Have You Logged While Reproducing This Bug?
Have none logged any, but a lot of people are complaining the same

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None

**Comment by dhaval47** [comment]
+1, Facing this issue

**Comment by dfrieling** [comment]
+1, any update on this?

**Comment by Science4me** [comment]
Think it is solved, check the latest update

**Comment by dfrieling** [comment]
I don't think so, I am using caldera 1.9.3 and it's still showing this behavior.

_WordPress Version: 5.6PHP Version: 7.4.13MySQL Version: 8.0.20Caldera Forms Version: 1.9.3WP_DEBUG: _´

@Science4me are you positive it's fixed in your installation?
