### ISSUE TITLE
Slug label doesn't return the correct value from dropdown

### ISSUE THREAD

**Issue by adamx12m** [CalderaWP/Caldera-Forms#717]
Caldera Forms Version 1.3.5.3 
WORDPRESS:	4.5.3
PHP INFO:	5.5.29
SERVER:		Apache/2.4.16

Using a dropdown contain 50 entries, the correct label entry for a given selection is not returned using %slug:label% if duplicate values are found.

Example, the dropdown contains 50 us states, using 'show value' enabled, each state contains the same email address except one state let's say Oklahoma that contains a different email address value.  Using a custom email template to display the state label because the email is being sent to value, eg. <strong>State:</strong> %state:label% , if you choose Oklahoma the label value is printed correctly, all other state selections display Wyoming in the email which is the last entry in the dropdown.

**Comment by Shelob9** [comment]
@adamx12m Can you please test with version 1.4-b-1 (the current-dev branch) please? This issue should be resolved. 

https://calderawp.com/doc/update-caldera-forms-latest-beta/

**Comment by adamx12m** [comment]
Installed Version 1.4.0-b-1, problem still exists.  When entering duplicate "values" for a given label, a error message shows below now stating "Values should be unique to determine which option is selected.".   All the value fields are highlighted in red border.

I'm able to to save the form, but the value from %state:label% is still the last entry in the dropdown since it contains duplicate values.

value            label
a@a.com    alabama
a@a.com    alaska
zz@a.com   arizona
a@a.com    arkansas
a@a.com    california

Just to be clear, if you choose alaska in the form, %state% as the recipient appears to work ok, just %state:label% in the template prints 'california' when it should print 'alaska'.  If you choose 'arizona' there is no issue.

**Comment by Shelob9** [comment]
Thanks for providing additional information. Unfortunately there is no way to make it work so you have multiple values that are the same. 

Your actual problem here is you want to you need conditional recipients. This is not a good way to solve that pprolem. One solution is to use multiple auto-responder processors, with a different email address for each one and use conditional logic to set which one will send. Another option is to use the caldera_forms_mailer filter to change the recipient based on a field value.
See: https://calderawp.com/doc/caldera_forms_mailer

If you need help implementing either of these solutions, please open a support ticket. CalderaWP.com/support

BTW I agree the UI error is bad for this. We will fix that via #719
